  # æ¨¡å¼è‡ªåŠ¨
mode: auto

  # ç½‘ç«™å›¾æ ‡ï¼ˆå¾…ä¿®æ”¹ï¼‰
favicon: /ghost-smile-line.svg

  # å¤´åƒï¼ˆï¼‰
avatar:
  url: /images/1.jpg
  status:
    enable: true
    emoji: ğŸ¤¡
    message: åŠªåŠ›ing

  # é¦–é¡µ
banner:
  enable: true
  title: åœ¥å¿ˆçš„å°ç«™
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line


    # å…¬å‘Š
notice:
  enable: true
  content: Thanks for check out my blog

  # èƒŒæ™¯ï¼ˆï¼‰
bg_image:
  enable: true
  url: https://s3.bmp.ovh/imgs/2022/03/46d47abde5b3b4aa.jpg
  dark: https://s1.ax1x.com/2022/04/05/qXP6JI.png
  # blur: 30px # è®¾ç½®èƒŒæ™¯æ¨¡ç³Šç¨‹åº¦
  opacity: 0.6

  # çƒŸèŠ±
fireworks:
  enable: true
  colors:
    - "102, 167, 221"
    - "	255,0,255"
    - "33, 78, 194"
    - "255,69,0"

    # èƒŒæ™¯ä¸æ ‡ç­¾
sidebar:
  bg_image: https://s1.ax1x.com/2022/03/31/qfDS9e.png
  bg_position: bottom 3rem center
  tagcloud:
    enable: false
    amount: 20
  # ç›®å½•
toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: å¾ˆé—æ†¾ï¼Œå’±æ²¡å†™å•¥ç›®å½•
  collapse: true

  # ä¿¡æ¯
post_meta:
  item_text: false
  created_at: true
  updated_at: true
  categories: true
  tags: true
  # ç‰ˆæƒ
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false  #true

  # æ‰“èµ
reward:
  enable: true
  icon: icon-hand-coin-line
  comment: I'm so cute. Please give me money.
  # url: https://github.com/YunYouJun/yunyoujun.github.io/issues/96
  methods:
    - name: æ”¯ä»˜å®
      path: https://s3.bmp.ovh/imgs/2022/03/a495286dcfde6bfa.bmp
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: https://s3.bmp.ovh/imgs/2022/03/1018089fdf3cd065.png
      color: "#12B7F5"
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: https://s3.bmp.ovh/imgs/2022/03/08ce21ed009e0f80.png
      color: "#2DC100"
      icon: ri:wechat-pay-line 
  # é©±åŠ¨
footer:
  powered:
    enable: true
  # é¡µè„š
  live_time:
    enable: true
    prefix: æœ¬åšå®¢å·²èŒèŒå“’åœ°è¿è¡Œ
    suffix: (â—'â—¡'â—)
    start_time: "2022-03-09T00:00:00"
  since: 2022
  icon:
    name: icon-cloud-line
    animated: true
    color: "#0078E7"
 

  # ä¸€è¨€
say:
  enable: true
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  # https://developer.hitokoto.cn/sentence/
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

    # å­—æ•°ç»Ÿè®¡
wordcount:
  enable: true
  count: true
  time: true
  # æ ‡ç­¾äº‘ï¼ˆè¯äº‘ï¼‰
wordcloud:
  enable: false
  height: 350
# è¯„è®ºï¼ˆå·²ä¿®æ”¹ï¼‰
github_discussions:
  enable: true
  username: weaving-dreams
  repository: weaving-dreams.github.io
comment:
  candidates:
    - waline
    # - giscus 
  tips:
    - ä¸è¦ä¸æˆ‘äº¤æµï¼Œæˆ‘ä»€ä¹ˆéƒ½ä¸ä¼šã€‚
  
# è¯„è®ºåŒº
waline:
  enable: true
  serverURL: https://waline-g166-f1ag5xjlk-weaving-dreams.vercel.app
  visitor: true
  comment: true
  emoji:
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/weibo

  
  locale:
    placeholder: æ¥éƒ½æ¥äº†ï¼Œè¯´ç‚¹ä»€ä¹ˆå§
    level0: 'ç‚¼ä½“'
    level1: 'ç‚¼æ°”'
    level2: 'ç­‘åŸº'
    level3: 'é‡‘ä¸¹'
    level4: 'å…ƒå©´'
    level5: 'åŒ–ç¥'

    
# badge: css/leaves.js
# vendors:
#   waline:
#     css: https://unpkg.com/@waline/client@v2/dist/waline.css     # Waline ä¸åŒç‰ˆæœ¬çš„ CDNï¼Œè§å®˜æ–¹æ–‡æ¡£
#     js:  https://unpkg.com/@waline/client@v2/dist/waline.js    # Waline ä¸åŒç‰ˆæœ¬çš„ CDNï¼Œè§å®˜æ–¹æ–‡æ¡£



  # èœå•
menu:
  custom:
    title: ç•™è¨€æ¿
    path: /about/#comment
    icon: ri:clipboard-line 

# æ¸¸æ ‡
cursor:
  enable: true

# Medium Zoom æ”¾å¤§é¢„è§ˆå›¾ç‰‡
medium_zoom: true

  # ç¤¾äº¤
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange

  - name: GitHub
    link: https://github.com/weaving-dreams
    icon: ri:github-line
    color: "#6e5494"

  - name: è¯­é›€
    link: https://www.yuque.com/yuqueyonghuvseqgc/wze6w2
    icon: ant-design:yuque-outlined
    color: "#007722"

  - name: å¾®åš
    link: https://weibo.com/u/6603251070
    icon: ri:weibo-line
    color: "#E6162D"

  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1475793651
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
    
  - name: å“”å“©å“”å“©
    link: https://space.bilibili.com/499227133?share_medium=android&share_plat=android&share_session_id=f72830f6-8f5f-413a-86d2-6043b1bd69eb&share_source=WEIXIN&share_tag=s_i&timestamp=1646642363&unique_k=pDXLBN4
    icon: ri:bilibili-line
    color: "#FF8EB3"

  - name: é…·å®‰
    link: http://www.coolapk.com/u/4097869
    icon: icon-kuancoolapk1
    color: "#007722"



  # é»˜å“€
mourn:
  enable: true
  days:
    - "4-4"
    - "9-18"

  # busuanzi
busuanzi:
  enable: true
  site_uv: true
  site_uv_icon: ri:user-line
  site_pv: true
  site_pv_icon: ri:eye-line
  page_pv: true
  page_pv_icon: ri:eye-line

  # ä¸€é”®å¤åˆ¶
codeblock:
  copy_btn: true



# ç›¸å†Œé›†
albums:
  enable: true

pages:
  - name: å‹è” links
    url: /links/
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: ri:women-line
    color: hotpink
  - name: ç›¸å†Œé›†
    url: /albums/
    icon: ri:gallery-line
    color: "#6e5494"


# girls:
#   enable: false

pjax:
  enable: true
  

head:
  js:
    async:
      # è¿™é‡Œæ˜¯ä½ ä» iconfont å¤„è·å¾—çš„å›¾æ ‡é“¾æ¥ã€‚
      iconfont: //at.alicdn.com/t/font_3319107_f11xxoznd2e.js


# æœ¬åœ°æœç´¢ and å¼•æ“æœç´¢
engine_search:
  enable: false
  href: "https://www.google.com/search?q=site:"
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: weaving-dreams.github.io
local_search:
  enable: true


